### PR TITLE
rollup without grunt

### PR DESCRIPTION
**Pull request by jgravois**
this PR is primarily a sanity check / discussion starter.

i was having a hard time understanding how `grunt-rollup` was actually being used in your gruntfile so i fell back on calling rollup directly to bundle/minify `portal.js` and its dependencies.  please confirm whether or not i understand your ultimate goal.
1. write your own code as ES6 modules
2. make sure you can import external AMD dependencies
3. concatenate, minify and resolve all source in a production build

is this right? are there any other module formats you'll need to import?

if so, hopefully this PR is a good next step.  after tweaking your `portal` and `request` modules, i was able to confirm that all the relevant code was accessible.

``` js
var test = new AgoAssistant.Portal({
  portalUrl: 'https://www.arcgis.com/'
})

test.version()
  .then(function(e) {
    console.log(e.currentVersion)
  })
```

### CODE REVIEW

**Comment by ecaldwell** [comment]
> 1. write your own code as ES6 modules
> 2. make sure you can import external AMD dependencies
> 3. concatenate, minify and resolve all source in a production build

I'm impressed you were able to decipher my goals from this messy branch! 👏  The real driving goal here is to support a more robust build system so I'd say your item 3 is really my item 1. 

#### concatenate, minify and resolve all source in a production build

I like what rollup _appears_ to offer so it seems as good as any for a first shot at this rewrite. 

#### make sure you can import external AMD dependencies

This is really critical because of all the third party libraries this app leverages. Over time, I think we'll be able to whittle these down (e.g. jquery-ui), but some of them are really core to the app (e.g. highlight.js).

#### write your own code as ES6 modules

The goal for rewriting portal.js in es6 (aside from my own practice) is to make it a little more organized, easier to extend, and easier to include in a build process. I originally used jquery in there because it was easy and it was already being used elsewhere in ago-assistant, but I think a simple API module like that is best done with as few dependencies as possible. 

So great work on getting portal.js to build. I'll start working through the rewrite of the other API functions as well as changing all of the `.done()` references to `.then()` in `main.js`.

**Comment by jgravois** [comment]
> I'd say your item 3 is really my item 1

i wasn't listing them in order of importance, but rather _chronologically_ :smile:

> ... because of all the third party libraries this app leverages

if you need a hand importing jquery-ui, highlight.js, etc. via rollup, i'm happy to help.  i'm hopeful that it will be pretty straightforward.

if you're happy with the approach i already sketched out, thats great, but we can continue playing around with the exports given that what we're attempting to bundle here is a self contained app (and not a library)

**Comment by ecaldwell** [comment]
> i wasn't listing them in order of importance, but rather chronologically

Ah, then yes...you nailed it.

> ...what we're attempting to bundle here is a self contained app (and not a library)

I'm confusing the matter here. I typically think of the portal module as a library (because I have aspirations to break it out on its own eventually). You're absolutely right though, we're bundling an app, not just a specific module.

I'm also interested that you had problems using `grunt-rollup` (or understanding my usage). I was not able to get it to run successfully (in fact, it would run indefinitely). I'll try to figure that out longer term as well.

**Comment by ecaldwell** [comment]
@jgravois I finished refactoring the portal.js library into module syntax (and other es6 goodness). Everything seems to be in good shape with a few dev related exceptions.
- `babel()` doesn't seem to be converting any of the code (e.g. changing `let` to `var`). I tried added the `es-2015` preset to no avail.
- the output of rollup is not getting minified. I get errors when I try to include `uglify()`.

Can you take a look and see if anything jumps out at you? Also, I renamed the branch to `dev/rollup`.

**Pull request merged**
